# Generated by Django 4.0.4 on 2022-07-07 11:12

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='secret',
            field=models.CharField(default='', max_length=128, verbose_name='secret'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(16,), **{}), max_length=16, unique=True, verbose_name='key'),
        ),
    ]
