# Generated by Django 3.2.12 on 2022-03-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'API token', 'verbose_name_plural': 'API tokens'},
        ),
    ]
