# Generated by Django 4.0.3 on 2022-04-18 11:01

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_token_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(32,), **{}), max_length=32, unique=True, verbose_name='key'),
        ),
    ]
