# Generated by Django 4.0.4 on 2022-11-11 13:17

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token_secret_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(12,), **{}), max_length=12, unique=True, verbose_name='key'),
        ),
    ]
