from collections.abc import Iterator, MutableMapping
from typing import Any

# This stub is in no way complete, it only contains the parts we actually use so that
# Mypy doesn't complain.
class ImageMetadata(MutableMapping[Any, Any]):
    @classmethod
    def from_buffer(cls, buffer_: bytes) -> ImageMetadata: ...
    def read(self) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
