# Generated by Django 4.0.3 on 2022-04-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='record_unique_for_content_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='record',
            name='object_pk',
        ),
    ]
