# Generated by Django 4.0.4 on 2022-07-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_collection_collectionitem_note_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(help_text='Title of the collection.', max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='asset',
            field=models.ForeignKey(help_text='The asset to place in the collection.', on_delete=django.db.models.deletion.CASCADE, to='libraries.asset', verbose_name='asset'),
        ),
    ]
