# Generated by Django 4.0.4 on 2022-07-07 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_collection_collectionitem_note_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_instance', related_query_name='%(class)s_instance', serialize=False, to='libraries.asset', verbose_name='asset reference')),
                ('metadata_checksum', models.BinaryField(db_index=True, default=None, help_text="Hash value of the image's metadata. This is used to attribute multiple variations of the same photo to a single asset.", max_length=32, null=True, verbose_name='metadata checksum')),
                ('main_path', models.CharField(default='', help_text='Path of the main image that should be used for generating thumbnails and other information.', max_length=255, verbose_name='main path')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='height')),
                ('aperture_size', models.DecimalField(decimal_places=1, help_text='Aperture / F-Stop value of the shot, in inverse. A value of 4 in this field implies an f-value of f/4.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='aperture size')),
                ('exposure_time', models.FloatField(help_text="The shot's exposure time, in seconds.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exposure time')),
                ('focal_length', models.FloatField(help_text='Focal length of the camera, in millimeters.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='focal length')),
                ('iso_value', models.PositiveIntegerField(null=True, verbose_name='ISO sensitivity value')),
                ('camera_make', models.CharField(blank=True, max_length=50, verbose_name='camera maker')),
                ('camera_model', models.CharField(blank=True, max_length=50, verbose_name='camera model')),
                ('blurhash', models.CharField(help_text='Blurhash textual representation that can be used for loading placeholders.', max_length=100, null=True, verbose_name='blurhash')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
            bases=('libraries.asset',),
        ),
    ]
