# Generated by Django 4.1.4 on 2023-01-24 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_exposure_program_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='aperture_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Aperture / F-Stop value of the shot, in inverse. A value of 4 in this field implies an f-value of f/4.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='aperture size'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exposure_time',
            field=models.FloatField(blank=True, help_text="The shot's exposure time, in seconds.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exposure time'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.FloatField(blank=True, help_text='Focal length of the camera, in millimeters.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='focal length'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ISO sensitivity value'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='metadata_checksum',
            field=models.BinaryField(blank=True, db_index=True, default=None, help_text="Hash value of the image's metadata. This is used to attribute multiple variations of the same photo to a single asset.", max_length=32, null=True, verbose_name='metadata checksum'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='width'),
        ),
    ]
