# Generated by Django 4.0.4 on 2022-05-29 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_height_alter_photo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exposure_time',
            field=models.FloatField(help_text="The shot's exposure time, in seconds.", null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='exposure time'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.FloatField(help_text='Focal length of the camera, in millimeters.', null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='focal length'),
        ),
    ]
