# Generated by Django 4.1.4 on 2023-01-24 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_aperture_size_alter_photo_exposure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='aperture_size',
            field=models.FloatField(blank=True, help_text='Aperture / F-Stop value of the shot, in inverse. A value of 4 in this field implies an f-value of f/4.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='aperture size'),
        ),
    ]
