# Generated by Django 4.0.4 on 2022-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_exposure_time_alter_photo_focal_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='main_path',
            field=models.CharField(default='', help_text='Path of the main image that should be used for generating thumbnails and other information.', max_length=255, verbose_name='main path'),
        ),
    ]
