# Generated by Django 4.1.5 on 2023-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_aperture_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lens_identifier',
            field=models.CharField(blank=True, help_text='Name or ID of the camera lens, if applicable.', max_length=100, verbose_name='lens identifier'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='software',
            field=models.CharField(blank=True, help_text='Name of the Software used to edit the image, if any.', max_length=100, verbose_name='software'),
        ),
    ]
