# Generated by Django 4.1.5 on 2023-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_metadata_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='metadata_checksum',
            field=models.BinaryField(blank=True, default=None, help_text="Hash value of the image's metadata and the library ID. This is used to attribute multiple variations of the same photo to a single asset.", max_length=32, null=True, unique=True, verbose_name='metadata checksum'),
        ),
    ]
