# Generated by Django 4.2.1 on 2023-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0008_alter_photo_metadata_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="blurhash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Blurhash textual representation that can be used for loading placeholders.",
                max_length=100,
                verbose_name="blurhash",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="main_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Path of the main image that should be used for generating thumbnails and other information.",
                max_length=255,
                verbose_name="main path",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="metadata_checksum",
            field=models.BinaryField(
                blank=True,
                default=None,
                help_text="Hash value of the image's metadata and the library ID. This is used to attribute multiple variations / renditions of the same photo to a single asset.",
                max_length=32,
                null=True,
                verbose_name="metadata checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("metadata_checksum__isnull", False)),
                fields=("metadata_checksum",),
                name="photos_unique_by_metadata",
            ),
        ),
    ]
