from enum import Enum

from PIL import Image

class PixelMode(Enum):
    RGB = ...
    RGBA = ...

class BlurhashDecodeError(Exception):
    pass

def encode(image: Image.Image | str, x_components: int, y_components: int) -> str: ...
def decode(
    blurhash: str, width: int, height: int, punch: float = ..., mode: PixelMode = ...
) -> Image.Image: ...
def is_valid_blurhash(bluhash: str) -> bool: ...
