from typing import overload

import numpy.typing

def base83_decode(base83_str: str) -> int: ...
def base83_encode(value: int, length: int) -> str: ...
def srgb_to_linear(value: int) -> float: ...
def sign_pow(value: float, exp: float) -> float: ...
def linear_to_srgb(value: float) -> int: ...
def blurhash_components(blurhash: str) -> tuple[int, int]: ...
def blurhash_encode(
    image: numpy.typing.ArrayLike,
    components_x: int = ...,
    components_y: int = ...,
    linear: bool = ...,
) -> str: ...
