from collections.abc import Sequence
from typing import Literal, overload

def base83_decode(base83_str: str) -> int: ...
def base83_encode(value: int, length: int) -> str: ...
def srgb_to_linear(value: int) -> float: ...
def sign_pow(value: float, exp: float) -> float: ...
def linear_to_srgb(value: float) -> int: ...
def blurhash_components(blurhash: str) -> tuple[int, int]: ...
@overload
def blurhash_encode(
    image: Sequence[tuple[float, float, float]],
    components_x: int = ...,
    components_y: int = ...,
    linear: Literal[True] = ...,
) -> str: ...
@overload
def blurhash_encode(
    image: Sequence[tuple[int, int, int]],
    components_x: int = ...,
    components_y: int = ...,
    linear: Literal[False] = False,
) -> str: ...
