# Generated by Django 4.0.3 on 2022-04-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_remove_record_record_unique_for_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericHandler',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_instance', related_query_name='%(class)s_instance', serialize=False, to='libraries.record')),
                ('initialized', models.BooleanField(default=False)),
                ('content', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
            bases=('libraries.record',),
        ),
    ]
