# Generated by Django 4.0.3 on 2022-05-01 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_alter_record_options_record_import_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryRecord',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_instance', related_query_name='%(class)s_instance', serialize=False, to='libraries.record', verbose_name='record reference')),
                ('media_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text="Timestamp associated with the record's medium. For records without a media file, this should be the creation date.", verbose_name='media timestamp')),
                ('media_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Real-world location associated with this entry.', null=True, srid=4326, verbose_name='media location')),
            ],
            options={
                'verbose_name': 'gallery record',
                'verbose_name_plural': 'gallery records',
            },
            bases=('libraries.record',),
        ),
        migrations.AddIndex(
            model_name='galleryrecord',
            index=models.Index(fields=['media_timestamp', 'record'], name='timestamp_filtering'),
        ),
        migrations.AddIndex(
            model_name='galleryrecord',
            index=models.Index(fields=['media_location', 'record'], name='location_filtering'),
        ),
    ]
