# Generated by Django 4.0.4 on 2022-05-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the album.', max_length=250, verbose_name='title')),
            ],
            options={
                'verbose_name': 'gallery asset',
                'verbose_name_plural': 'gallery assets',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(help_text='The album the asset is placed in.', on_delete=django.db.models.deletion.CASCADE, to='gallery.album', verbose_name='album')),
                ('asset', models.ForeignKey(help_text='The gallery asset to place in the album.', on_delete=django.db.models.deletion.CASCADE, to='gallery.galleryasset', verbose_name='asset')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='assets',
            field=models.ManyToManyField(related_name='albums', related_query_name='album', through='gallery.AlbumItem', to='gallery.galleryasset'),
        ),
    ]
