# Generated by Django 4.0.3 on 2022-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryrecord',
            name='stack_key',
            field=models.IntegerField(blank=True, default=None, help_text='Identifier that is the same for all entries on a stack.', null=True, verbose_name='stack key'),
        ),
        migrations.AddField(
            model_name='galleryrecord',
            name='stack_representative',
            field=models.BooleanField(default=False, help_text="Designates whether this records is its stack's representative. It will be shown as the cover element when the stack is rendered.", verbose_name='stack representative status'),
        ),
        migrations.AddConstraint(
            model_name='galleryrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('stack_representative', True)), fields=('stack_key', 'stack_representative'), name='unique_representative_per_stack'),
        ),
        migrations.AddConstraint(
            model_name='galleryrecord',
            constraint=models.CheckConstraint(check=models.Q(('stack_key__isnull', False), ('stack_representative', False), _connector='OR'), name='not_a_representative_when_unstacked'),
        ),
        migrations.AlterModelTable(
            name='galleryrecord',
            table='gallery_record',
        ),
    ]
