# Generated by Django 4.0.3 on 2022-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryrecord_stack_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryrecord',
            name='stack_key',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Identifier that is the same for all entries on a stack.', null=True, verbose_name='stack key'),
        ),
    ]
