# Generated by Django 4.0.3 on 2022-05-09 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_galleryrecord_stack_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('gallery_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_instance', related_query_name='%(class)s_instance', serialize=False, to='gallery.galleryrecord', verbose_name='gallery record reference')),
                ('content', models.TextField(help_text='Content of the note, which should be rendered using the markdown syntax.', verbose_name='note content')),
            ],
            options={
                'abstract': False,
            },
            bases=('gallery.galleryrecord',),
        ),
    ]
