# Generated by Django 4.0.3 on 2022-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryrecord',
            options={'get_latest_by': 'media_timestamp', 'ordering': ('media_timestamp',), 'verbose_name': 'gallery record', 'verbose_name_plural': 'gallery records'},
        ),
        migrations.AlterField(
            model_name='galleryrecord',
            name='media_timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text="Timestamp associated with the record's medium. For records without a media file, this should be the creation date.", verbose_name='media timestamp'),
        ),
    ]
