# Generated by Django 3.2.11 on 2022-03-03 16:09

from django.db import migrations
import tumpara.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tumpara.accounts.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='usermembership',
            old_name='object_id',
            new_name='object_pk',
        ),
    ]
