# Generated by Django 3.2.11 on 2022-03-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220303_1609'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usermembership',
            name='user_object_membership_unique',
        ),
        migrations.AddConstraint(
            model_name='usermembership',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_pk'), name='user_object_membership_unique'),
        ),
    ]
