# Generated by Django 3.2.11 on 2022-03-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220303_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_name',
            new_name='username',
        ),
    ]
